spring:
  data:
    mongodb:
      username: admin
      password: pass
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
    port: 8090
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
    
